<style>
    #nette-debug .nette-featuresPanel,
    #tracy-debug .nette-featuresPanel { min-width: 700px; }
    #nette-debug .nette-featuresPanel h2,
    #tracy-debug .nette-featuresPanel h2 { font-size: 22px; font-weight: bold; }
    #nette-debug .nette-featuresPanel small,
    #tracy-debug .nette-featuresPanel small { font-size: 70%; font-weight: normal; }
    #nette-debug .nette-featuresPanel code,
    #tracy-debug .nette-featuresPanel code { font-size: 100%; font-weight: inherit; }
    #nette-debug .nette-featuresPanel table,
    #tracy-debug .nette-featuresPanel table { width: 100%; }
    #nette-debug .nette-featuresPanel table th,
    #tracy-debug .nette-featuresPanel table th { text-align: right; }
</style>
<div class="nette-inner tracy-inner">
	<table>
		<tr><th>Feature</th><th>Context</th><th>Result</th></tr>
		<?php
		foreach ($evaluatedFeatures as $data):
			$feature	 = $data['feature'];
			$context	 = $data['context'];
			$result		 = $data['result'];
			$conditions	 = $data['conditions'];

			$dump = [
				$feature => [
					'context'	 => $context,
					'conditions' => $conditions,
					'result'	 => $result,
				]
			];
			?>
			<tr>
				<td><strong><?php echo $feature ?></strong></td>
				<td>
					<div class="nette-inner tracy-inner nette-featuresPanel">
						<?php echo $click($context); ?>
					</div>
				</td>
				<?php /*
				  <td>
				  <div class="nette-inner tracy-inner nette-featuresPanel">
				  <?php echo $click($dump); ?>
				  </div>
				  </td>

				  <td>
				  <div class="nette-inner tracy-inner nette-featuresPanel">
				  <?php echo $click($conditions); ?>
				  </div>
				  </td>
				 *  *
				 */
				?>
				<td>
					<strong><?php echo $result ? 'Active' : 'Disabled' ?></strong>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>